### PR TITLE
Implement EventEmitter.remove_all_listeners()

### PR DESCRIPTION
**Pull request by Zearin**
As described here: https://nodejs.org/api/events.html#events_emitter_removealllisteners_event

### CODE REVIEW

**Comment by kevinconway** [comment]
Looks like this is failing the pep8 and pep257 checks: https://travis-ci.org/asyncdef/eventemitter/jobs/95354678.

**Comment by Zearin** [comment]
I’ve fixed the failing PEP checks, but the test fails for the latest `dev` and `nightly` builds.  I do not understand the failure.  

Here’s the precise line where the failure occurs:
https://travis-ci.org/asyncdef/eventemitter/jobs/96044135#L182

**Comment by Zearin** [comment]
@kevinconway Anything else I can do on this?

**Comment by kevinconway** [comment]
I think this is a good addition. I would ask that you add a test for the new code paths to make sure any future changes preserve the expected behaviour. There are some tests for similar functionality here: https://github.com/asyncdef/eventemitter/blob/master/eventemitter/test_emitter.py#L96.

**Comment by Zearin** [comment]
Okay!  Will have a test or two ready shortly.

**Comment by Zearin** [comment]
Ta-da

**Comment by kevinconway** [comment]
:+1:

**Comment by kevinconway** [comment]
Your patch is now up in v0.2.0 on PyPi.

**Comment by Zearin** [comment]
Awesome!  Thanks. :)

**Pull request merged**
